[package]
name = "steganography-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aes-gcm = { version = "0.10", default-features = false, features = ["aes", "alloc"] }
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
sha2 = { version = "0.10", default-features = false }
hmac = { version = "0.12", default-features = false }

[profile.release]
opt-level = "s"
