module.exports = {
  keywords: [
    { word: "ignore previous", weight: 30 },
    { word: "ignore all previous", weight: 40 },
    { word: "forget everything", weight: 35 },
    { word: "disregard previous", weight: 30 },
    { word: "disregard all previous", weight: 40 },
    { word: "ignore the instructions", weight: 35 },
    { word: "ignore your instructions", weight: 35 },
    { word: "you are now", weight: 25 },
    { word: "pretend to be", weight: 30 },
    { word: "act as", weight: 20 },
    { word: "roleplay", weight: 20 },
    { word: "role play", weight: 20 },
    { word: "new instructions", weight: 25 },
    { word: "follow these rules", weight: 25 },
    { word: "override", weight: 30 },
    { word: "bypass", weight: 35 },
    { word: "reveal your", weight: 35 },
    { word: "show your", weight: 25 },
    { word: "tell me your", weight: 25 },
    { word: "what are your", weight: 20 },
    { word: "system prompt", weight: 35 },
    { word: "initial prompt", weight: 30 },
    { word: "original prompt", weight: 30 },
    { word: "ignore the system", weight: 35 },
    { word: "you are a", weight: 15 },
    { word: "from now on", weight: 30 },
    { word: "starting now", weight: 30 },
    { word: "reset your", weight: 35 },
    { word: "clear your memory", weight: 40 },
    { word: "forget your", weight: 35 },
    { word: "忽略之前的", weight: 35 },
    { word: "忽略所有之前的", weight: 40 },
    { word: "忘记一切", weight: 35 },
    { word: "无视之前的", weight: 30 },
    { word: "忽略指令", weight: 35 },
    { word: "忽略你的指令", weight: 35 },
    { word: "你现在是", weight: 25 },
    { word: "假装是", weight: 30 },
    { word: "扮演", weight: 20 },
    { word: "角色扮演", weight: 20 },
    { word: "新的指令", weight: 25 },
    { word: "遵循这些规则", weight: 25 },
    { word: "覆盖", weight: 20 },
    { word: "绕过", weight: 25 },
    { word: "透露你的", weight: 30 },
    { word: "显示你的", weight: 25 },
    { word: "告诉我你的", weight: 25 },
    { word: "你的是什么", weight: 20 },
    { word: "系统提示", weight: 35 },
    { word: "初始提示", weight: 30 },
    { word: "原始提示", weight: 30 },
    { word: "忽略系统", weight: 35 },
    { word: "从现在开始", weight: 20 },
    { word: "现在开始", weight: 20 },
    { word: "重置你的", weight: 25 },
    { word: "清除记忆", weight: 30 },
    { word: "忘记你的", weight: 25 },
  ],

  regexPatterns: [
    { pattern: /ignore\s+(?:all\s+)?(?:previous|prior)\s+(?:instructions|directives|commands)?/i, weight: 40 },
    { pattern: /disregard\s+(?:all\s+)?(?:previous|prior)\s+(?:instructions|directives|commands)?/i, weight: 40 },
    { pattern: /forget\s+(?:everything|all\s+instructions)/i, weight: 35 },
    { pattern: /you\s+(?:are|will\s+be)\s+(?:now|henceforth)\s+(?:a|an|the)/i, weight: 30 },
    { pattern: /pretend\s+(?:you\s+are|to\s+be)/i, weight: 35 },
    { pattern: /act\s+as\s+(?:if\s+you\s+were|like)/i, weight: 25 },
    { pattern: /(?:new|different)\s+(?:instructions|rules|directives)/i, weight: 30 },
    { pattern: /override\s+(?:all\s+)?(?:previous|prior)/i, weight: 35 },
    { pattern: /bypass\s+(?:the\s+)?(?:system|instructions|security)/i, weight: 40 },
    { pattern: /bypass\s+all\s+(?:your\s+)?(?:security|safety)/i, weight: 45 },
    { pattern: /(?:reveal|tell|show)\s+(?:me\s+)?(?:your|the)\s+(?:system|initial|original)\s+prompt/i, weight: 45 },
    { pattern: /what\s+(?:is|are)\s+(?:your|the)\s+(?:system|initial|original)\s+prompt/i, weight: 40 },
    { pattern: /from\s+now\s+on\s+you\s+(?:are|will)/i, weight: 35 },
    { pattern: /忽略(?:所有)?(?:之前|先前|以前)的(?:指令|指示|命令)?/i, weight: 40 },
    { pattern: /忘记(?:一切|所有指令|之前的内容)/i, weight: 35 },
    { pattern: /你(?:现在|将)(?:是|成为|扮演)/i, weight: 30 },
    { pattern: /假装(?:你是|成为)/i, weight: 35 },
    { pattern: /(?:新的|不同的)(?:指令|规则|要求)/i, weight: 30 },
    { pattern: /覆盖(?:所有)?(?:之前|先前)的/i, weight: 35 },
    { pattern: /绕过(?:系统|安全|限制|检测)/i, weight: 35 },
    { pattern: /(?:透露|告诉|显示)(?:我)?(?:你的|系统|初始|原始)提示/i, weight: 45 },
    { pattern: /(?:你的|系统|初始|原始)提示(?:是)?(?:什么)?/i, weight: 40 },
    { pattern: /从现在开始你(?:是|要|将)/i, weight: 25 },
  ],

  threshold: 50,
};
